//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.AZ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.AZ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Sussex County Council.
        /// </summary>
        internal static string CouncilNameCounty {
            get {
                return ResourceManager.GetString("CouncilNameCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastbourne Borough Council.
        /// </summary>
        internal static string CouncilNameEastbourne {
            get {
                return ResourceManager.GetString("CouncilNameEastbourne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastings Borough Council.
        /// </summary>
        internal static string CouncilNameHastings {
            get {
                return ResourceManager.GetString("CouncilNameHastings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lewes District Council.
        /// </summary>
        internal static string CouncilNameLewes {
            get {
                return ResourceManager.GetString("CouncilNameLewes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rother District Council.
        /// </summary>
        internal static string CouncilNameRother {
            get {
                return ResourceManager.GetString("CouncilNameRother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealden District Council.
        /// </summary>
        internal static string CouncilNameWealden {
            get {
                return ResourceManager.GetString("CouncilNameWealden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show services provided by:.
        /// </summary>
        internal static string SearchCouncilsPrompt {
            get {
                return ResourceManager.GetString("SearchCouncilsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form uses JavaScript, which is disabled or unavailable in your browser. Instead, to show services only from selected councils, click the &quot;Search&quot; button..
        /// </summary>
        internal static string SearchNoScript {
            get {
                return ResourceManager.GetString("SearchNoScript", resourceCulture);
            }
        }
    }
}
